# Initialize Jira PostgreSQL database
gosu postgres psql -q <<- EOSQL
	CREATE ROLE $JIRA_DB_USER WITH LOGIN PASSWORD '$JIRA_DB_PASS' VALID UNTIL 'infinity';
	CREATE DATABASE $JIRA_DB_NAME WITH ENCODING 'UNICODE' LC_COLLATE 'C' LC_CTYPE 'C' TEMPLATE template0;
	CREATE DATABASE $CONF_DB_NAME WITH ENCODING 'UNICODE' LC_COLLATE 'C' LC_CTYPE 'C' TEMPLATE template0;
	CREATE DATABASE $FISH_DB_NAME WITH ENCODING 'UNICODE' LC_COLLATE 'C' LC_CTYPE 'C' TEMPLATE template0;
	CREATE DATABASE $STASH_DB_NAME WITH ENCODING 'UNICODE' LC_COLLATE 'C' LC_CTYPE 'C' TEMPLATE template0;
	CREATE DATABASE $BAMBOO_DB_NAME WITH ENCODING 'UNICODE' LC_COLLATE 'C' LC_CTYPE 'C' TEMPLATE template0;
EOSQL
